# Form implementation generated from reading ui file 'przyklady\interfejs_nr1.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 530, 1021, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAnuluj = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnAnuluj.setObjectName("btnAnuluj")
        self.horizontalLayout.addWidget(self.btnAnuluj)
        self.btnSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSave.setFlat(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 1021, 511))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 21))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuo_programie = QtWidgets.QMenu(self.menubar)
        self.menuo_programie.setObjectName("menuo_programie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOtw_rz = QtGui.QAction(MainWindow)
        self.actionOtw_rz.setObjectName("actionOtw_rz")
        self.actionZamknij = QtGui.QAction(MainWindow)
        self.actionZamknij.setObjectName("actionZamknij")
        self.actionNowy = QtGui.QAction(MainWindow)
        self.actionNowy.setObjectName("actionNowy")
        self.menuPlik.addAction(self.actionNowy)
        self.menuPlik.addAction(self.actionOtw_rz)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionZamknij)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuo_programie.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAnuluj.setText(_translate("MainWindow", "Anuluj"))
        self.btnSave.setText(_translate("MainWindow", "Zapisz"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.menuo_programie.setTitle(_translate("MainWindow", "o programie"))
        self.actionOtw_rz.setText(_translate("MainWindow", "Otwórz"))
        self.actionZamknij.setText(_translate("MainWindow", "Zamknij"))
        self.actionNowy.setText(_translate("MainWindow", "Nowy"))
